name: Deploy Docker and restart
on:
  push:
    branches:
      - production
jobs:
  publish_docker_image_github:
    name: Build and publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          repository: schillingsebastian/quatsch.io/server
          tag_with_ref: true
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MUSIC_BOT_HOST }}
          username: ${{ secrets.MUSIC_BOT_HOST_USERNAME }}
          password: ${{ secrets.MUSIC_BOT_HOST_PASSWORD }}
          script: |
            docker log in
            docker pull docker.pkg.github.com/schillingsebastian/quatsch.io/server:latest
            docker stop quatsch.io
            docker rm quatsch.io
            docker run --name=quatsch.io --restart=always \
              -e -d docker.pkg.github.com/schillingsebastian/quatsch.io/server